'use client';
import {useEffect,useState} from 'react';
import type {ComponentType} from 'react'; import {services as initialServices,cases as initialCases} from '../../lib/data'; import {Save,Plus,Trash2,Settings,FileText,Briefcase,Users,BarChart3,Lock} from 'lucide-react';
type Lead={name:string;email:string;company:string;service:string;message:string;status:string};
export default function Admin(){const [logged,setLogged]=useState(false);const [pass,setPass]=useState('');const [tab,setTab]=useState('overview');const [headline,setHeadline]=useState('MARKETING IN MOTION.');const [desc,setDesc]=useState('Orbitly connects strategy, advertising, search and data into marketing systems designed to help ambitious businesses move forward.');const [seo,setSeo]=useState({title:'Orbitly — Digital Marketing Agency',description:'Strategy, advertising, search and data for measurable growth.',ga4:'',gtm:'',googleAds:'',meta:'',clarity:''});const [leads,setLeads]=useState<Lead[]>([]);const [saved,setSaved]=useState(false);
useEffect(()=>{setLogged(sessionStorage.getItem('orbitly-admin')==='1');try{const c=JSON.parse(localStorage.getItem('orbitly-content')||'null');if(c){setHeadline(c.headline);setDesc(c.desc)}}catch{} try{const s=JSON.parse(localStorage.getItem('orbitly-settings')||'null');if(s)setSeo(s)}catch{} try{const l=JSON.parse(localStorage.getItem('orbitly-leads')||'[]');setLeads(l)}catch{}},[]);
const login=(e:any)=>{e.preventDefault();if(pass==='orbitly-admin'){sessionStorage.setItem('orbitly-admin','1');setLogged(true)}else alert('Demo password: orbitly-admin')}; const save=()=>{localStorage.setItem('orbitly-content',JSON.stringify({headline,desc}));localStorage.setItem('orbitly-settings',JSON.stringify(seo));setSaved(true);setTimeout(()=>setSaved(false),1800)};
if(!logged)return <div className="min-h-screen grid place-items-center bg-[#111] p-6"><form onSubmit={login} className="card p-8 w-full max-w-md"><Lock className="mb-5"/><p className="eyebrow">Orbitly Admin</p><h1 className="text-4xl font-black mt-3">Private dashboard</h1><p className="text-[#666] mt-3">Demo-ready admin area. Replace authentication with your production provider before launch.</p><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Admin password" className="w-full border-b border-black/20 py-4 mt-8 outline-none"/><button className="btn btn-dark w-full justify-center mt-6">Login</button></form></div>;
const nav: Array<{id:string; label:string; Icon: ComponentType<{size?: number}>}>=[{id:'overview',label:'Overview',Icon:BarChart3},{id:'content',label:'Website Content',Icon:FileText},{id:'services',label:'Services',Icon:Briefcase},{id:'cases',label:'Case Studies',Icon:Briefcase},{id:'leads',label:'Leads',Icon:Users},{id:'settings',label:'SEO & Tracking',Icon:Settings}]; return <div className="min-h-screen bg-[#f5f4ef]"><aside className="fixed inset-y-0 left-0 w-64 bg-[#111] text-white p-6 hidden md:block"><div className="font-black text-2xl tracking-[-.08em]">ORBITLY<span className="text-lime">.</span></div><p className="eyebrow text-white/40 mt-10">Admin</p><div className="mt-5 grid gap-2">{nav.map(({id,label,Icon})=><button onClick={()=>setTab(id)} className={`text-left p-3 rounded-xl flex gap-3 items-center ${tab===id?'bg-white/10':''}`} key={id}><Icon size={17}/>{label}</button>)}</div><button onClick={()=>{sessionStorage.removeItem('orbitly-admin');setLogged(false)}} className="absolute bottom-7 text-white/50 text-sm">Log out</button></aside><main className="md:ml-64 p-5 md:p-10 max-w-6xl"> <div className="flex justify-between items-center"><div><p className="eyebrow">Orbitly Admin</p><h1 className="text-4xl font-black mt-2">{nav.find(n=>n.id===tab)?.label}</h1></div><button onClick={save} className="btn btn-dark"><Save size={17}/>{saved?'Saved':'Save changes'}</button></div>
{tab==='overview'&&<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-10">{[['Pages','07'],['Services',String(initialServices.length)],['Case Studies',String(initialCases.length)],['Leads',String(leads.length)]].map(([a,b])=><div className="card p-6" key={a}><p className="eyebrow">{a}</p><p className="text-4xl font-black mt-5">{b}</p></div>)}</div>}
{tab==='content'&&<div className="card p-7 mt-8 max-w-3xl"><label className="eyebrow">Homepage Hero Heading</label><input value={headline} onChange={e=>setHeadline(e.target.value)} className="w-full border-b border-black/20 py-4 text-2xl font-bold outline-none"/><label className="eyebrow block mt-8">Hero Description</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={5} className="w-full border border-black/10 rounded-xl p-4 mt-2 outline-none"/><p className="text-xs text-[#777] mt-4">This demo stores content in browser localStorage. Connect your database/API to make it multi-user and persistent across devices.</p></div>}
{tab==='services'&&<div className="grid md:grid-cols-2 gap-4 mt-8">{initialServices.map(s=><div className="card p-6" key={s.slug}><p className="eyebrow">Service</p><h2 className="text-2xl font-black mt-3">{s.title}</h2><p className="text-[#666] mt-2">{s.description}</p><button className="btn btn-light mt-5"><Plus size={15}/>Edit / extend</button></div>)}</div>}
{tab==='cases'&&<div className="grid md:grid-cols-2 gap-4 mt-8">{initialCases.map(c=><div className="card p-6" key={c.slug}><p className="eyebrow">{c.industry}</p><h2 className="text-2xl font-black mt-3">{c.title}</h2><p className="text-[#666] mt-2">{c.challenge}</p><button className="btn btn-light mt-5"><Plus size={15}/>Edit / extend</button></div>)}</div>}
{tab==='leads'&&<div className="card overflow-hidden mt-8"><div className="p-6 border-b border-black/10 font-bold">Lead inbox</div>{leads.length===0?<p className="p-8 text-[#666]">No leads yet. Connect the contact form to an API/database to populate this inbox.</p>:leads.map((l,i)=><div className="p-5 border-b border-black/10 flex justify-between" key={i}><div><b>{l.name}</b><p className="text-sm text-[#666]">{l.email} · {l.company}</p></div><span>{l.status}</span></div>)}</div>}
{tab==='settings'&&<div className="card p-7 mt-8 max-w-3xl space-y-6">{[['title','SEO Title'],['description','Meta Description'],['ga4','GA4 Measurement ID'],['gtm','Google Tag Manager ID'],['googleAds','Google Ads ID'],['meta','Meta Pixel ID'],['clarity','Microsoft Clarity ID']].map(([key,label])=><div key={key}><label className="eyebrow">{label}</label><input value={(seo as any)[key]} onChange={e=>setSeo({...seo,[key]:e.target.value})} className="w-full border-b border-black/20 py-3 outline-none"/></div>)}<p className="text-xs text-[#777]">Production note: connect these settings to your server/database and render tracking scripts conditionally after consent where required.</p></div>}
</main></div>}
